# https://taskfile.dev

version: '3'

tasks:
  docker:
    desc: Build and run the docker image
    cmds:
      - sudo docker build -t zferg/simple-http .
      - sudo docker run --rm -p 8080:8080 zferg/simple-http